name: Update gist with WakaTime stats
on:
  schedule: # 参考https://github.com/import-yuefeng/waka-box/commit/e0914455c96e8fbaf06c5a118e6de730d9c22fcf
    - cron: "* */3 * * *" # */10 * * * *每10分钟 action，方便调试:https://z-index.me/2020/05/14/Github-Weekly-WakaTime/；原来"0 0 * * *" 
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: StevenJokes/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 7ef1d9c8175f2379fe0313ae353524b8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
